# Uncomment the following line to enable deep sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y

# # Uncomment the following lines to enable the Nice!view Display
# CONFIG_ZMK_DISPLAY=y
# CONFIG_SSD1306=y
# CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

# Battery
# https://zmk.dev/docs/config/battery#peripheral-battery-monitoring
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# Disable the WPM widget
# CONFIG_ZMK_WIDGET_WPM_STATUS=n
# Display battery as n%
# CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
# Display layer
# CONFIG_ZMK_WIDGET_LAYER_STATUS=y
# Display current output
# CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

## RGB Backlight
## ZMK doesn't support per-key backlighting. The only lighting code that works with RGB LEDs is the underglow code, hence the suggestion to add your backlight LEDs to be part of underglow
CONFIG_ZMK_BACKLIGHT=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

## OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# Nice OLED
# CONFIG_NICE_OLED_WIDGET_WPM=n
# CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
# CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=n
# CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_LUNA=n
# CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=n
# CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_LUNA=n